### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by chenzean** [LilLouis5/Vision-Mamba-#1]
(pytorch_linux) chenzean@Desktop:~/Vision-Mamba--main$ python Vim.py
Traceback (most recent call last):
  File "Vim.py", line 468, in <module>
    test()
  File "Vim.py", line 445, in test
    model = VisionMamba(
  File "Vim.py", line 257, in __init__
    [
  File "Vim.py", line 258, in <listcomp>
    create_block(
  File "Vim.py", line 154, in create_block
    norm_cls=partial(
TypeError: the first argument must be callable

博主，我在运行代码的时候遇到这个问题了需要如何修改呢？

**Comment by NianWang-HJJGCDX** [comment]
这个只是没有加载上RMSNorm，所以partial没有识别第一个参数fun,因为他敲错了,是ssm而不是smm
把
try:
    from mamba_smm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn
改为
try:
  from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn

**Comment by chenzean** [comment]
噢噢噢噢好滴，谢谢up，
此外，那个发现还有一个小错误：(可能是我自己改错了)
self.head = nn.Linear(self.num_features, num_classes) if num_classes > 0 else nn.Identity()
那边缩进有点问题。
![image](https://github.com/LilLouis5/Vision-Mamba-/assets/107561504/2d39f9b5-338d-48ae-8d15-10ced1384100)
这样就可以了
最后想问一下up，VisionRotaryEmbeddingFast是报错的吧？

**Comment by chenzean** [comment]
我好像是因为mamba_smm文件里面有个库没有安装导致的

**Comment by XiaozhenQiao** [comment]
> 噢噢噢噢好滴，谢谢up， 此外，那个发现还有一个小错误：(可能是我自己改错了) self.head = nn.Linear(self.num_features, num_classes) if num_classes > 0 else nn.Identity() 那边缩进有点问题。 ![image](https://private-user-images.githubusercontent.com/107561504/328072356-2d39f9b5-338d-48ae-8d15-10ced1384100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTcwNjgsIm5iZiI6MTcxNTM5Njc2OCwicGF0aCI6Ii8xMDc1NjE1MDQvMzI4MDcyMzU2LTJkMzlmOWI1LTMzOGQtNDhhZS04ZDE1LTEwY2VkMTM4NDEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzA2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWVjYjBjMzA5NGI0MjQ4MDg5Mzk5YzMxNmE0ZGNlMGM5NWI1MDMxM2EwNDAxMzcyMDNmNTFkNzEyODJkYzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vLDjatKSiYfBIcOoNawbatFLW3p8wE1KeHrmh-iewv4) 这样就可以了 最后想问一下up，VisionRotaryEmbeddingFast是报错的吧？

我也有这个问题，请问是·什么问题呀？怎么解决的呀？

**Comment by chenzean** [comment]
哪个问题？
你的图片我发不开

**Comment by XiaozhenQiao** [comment]
> VisionRotaryEmbeddingFast是报错的

VisionRotaryEmbeddingFast是报错的,就是这个问题，感谢了

**Comment by chenzean** [comment]
VisionRotaryEmbeddingFast是不是文件里面没有呢

**Comment by XiaozhenQiao** [comment]
> VisionRotaryEmbeddingFast是不是文件里面没有呢

是呀，这个ViM代码里面也没定义VisionRotaryEmbeddingFast，我在想是不是在一个第三方库里面，不过我也不知道是哪个库了

**Comment by chenzean** [comment]
他那个代码我后面没有跑过

**Comment by chenzean** [comment]
你可以看一下最新的up主好像更新了

**Comment by XiaozhenQiao** [comment]
好嘞，感谢

**Comment by 5huanghuai** [comment]
> > VisionRotaryEmbeddingFast是不是文件里面没有呢
> 
> 是呀，这个ViM代码里面也没定义VisionRotaryEmbeddingFast，我在想是不是在一个第三方库里面，不过我也不知道是哪个库了

最简单的方法就是在初始化VisionMamba时,将if_rope 设置为false

**Comment by 6eternal6** [comment]
> 这个只是没有加载上RMSNorm，所以partial没有识别第一个参数fun,因为他敲错了,是ssm而不是smm 把 try: from mamba_smm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn 改为 try: from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn

您好，我在from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn时，会报错显示__init__函数中没有layernorm，但我看了__init__这就是定义的一个空文件，这是什么问题呀？

**Comment by ZZZyyyF12123** [comment]
这个项目，把up视频说的那个py文件改了之后
然后把ISSUE[chenzean]这个同学问的问题改了就可以正常运行

**Comment by ZhaohuiZhang0809** [comment]
补充一下，__version__ = "2.2.2" ，改为了 from mamba_ssm.ops.triton.layer_norm import RMSNorm, layer_norm_fn, rms_norm_fn

**Comment by hgdzhx** [comment]
> > 这个只是没有加载上RMSNorm，所以partial没有识别第一个参数fun,因为他敲错了,是ssm而不是smm 把 try: from mamba_smm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn 改为 try: from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn
> 
> 您好，我在from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn时，会报错显示__init__函数中没有layernorm，但我看了__init__这就是定义的一个空文件，这是什么问题呀？

请问解决了吗？我“causal_conv1d-1.2.1 + mamba_ssm-2.2.4 ” 依旧存在“from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn”没有找到引用这个问题

**Comment by deeponefish** [comment]
你好，我有个问题想请教。我跑训练的时候报错TypeError: Mamba.__init__() got an unexpected keyword argument 'bimamba_type'是因为版本的问题吗？可以如何解决？

**Comment by 6eternal6** [comment]
可以换个版本试一下 我没遇到过这个问题




 lvke
***@***.***







Original:
From: ***@***.***> Date: 2025-03-12 01:27:10 To: ***@***.***> Cc: ***@***.***>, ***@***.***> Subject: Re: [LilLouis5/Vision-Mamba-] 代码问题 (Issue #1)你好，我有个问题想请教。我跑训练的时候报错TypeError: Mamba.init() got an unexpected keyword argument 'bimamba_type'是因为版本的问题吗？可以如何解决？
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
deeponefish left a comment (LilLouis5/Vision-Mamba-#1)
你好，我有个问题想请教。我跑训练的时候报错TypeError: Mamba.init() got an unexpected keyword argument 'bimamba_type'是因为版本的问题吗？可以如何解决？

**Comment by 6eternal6** [comment]
> 你好，我有个问题想请教。我跑训练的时候报错TypeError: Mamba.**init**() got an unexpected keyword argument 'bimamba_type'是因为版本的问题吗？可以如何解决？
换个版本试试，新版本似乎与旧版本有差，之前没遇到过
